# Generated by Django 5.2.4 on 2026-02-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salry',
            new_name='salary',
        ),
    ]
